format = """
$fill\
[î‚¶](fg:#deddda)\
$character\
[î‚¼](fg:#deddda bg:#1a5fb4)\
$cmd_duration\
[î‚´ ](fg:#1a5fb4)\
$line_break\
[î‚¶](fg:#1a5fb4)\
$username\
$hostname\
[î‚¼](fg:#1a5fb4 bg:#1c71d8)\
$directory\
[î‚¼](fg:#1c71d8 bg:#3584e4)\
$git_branch\
$git_status\
[î‚¼](fg:#3584e4 bg:#62a0ea)\
$python\
[î‚¼](fg:#62a0ea bg:#99c1f1)\
$docker_context\
[î‚¼](fg:#99c1f1 bg:#deddda)\
$time\
[î‚´ ](fg:#deddda)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
symbol = ' '

[character]
format = '[$symbol]()'
success_symbol = '[ï˜](fg:green bg:#deddda)'
error_symbol = '[ï—](fg:red bg:#deddda)'

[cmd_duration]
style = "fg:bright-white bg:#1a5fb4"
format = '[ $duration]($style)'
min_time = 0

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:bright-white bg:#1a5fb4"
style_root = "fg:bright-white bg:#1a5fb4"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[hostname]
style = "fg:bright-white bg:#1a5fb4"
format = '[ @ $hostname ]($style)'
disabled = false # Disabled by default

[directory]
style = "fg:bright-white bg:#1c71d8"
format = "[ $path ]($style)"
read_only_style = "fg:red"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# For english use
"Pictures" = "ğŸ–¼ï¸ "
"Documents" = "ğŸ—ƒï¸ "
"Downloads" = "â¬‡ï¸ "
"Music" = "ğŸ¹ "
"Videos" = "ğŸ“¼ "
# For german use
"Bilder" = "ğŸ–¼ï¸ "
"Dokumente" = "ğŸ—ƒï¸ "
"Musik" = "ğŸ¹ "
"Videos" = "ğŸ“¼ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

# Git
[git_branch]
symbol = "îœ¥"
style = "fg:bright-white bg:#3584e4"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:bright-white bg:#3584e4"
format = '[ $all_status$ahead_behind ]($style)'

# Versions
[python]
symbol = "ğŸ"
style = "fg:black bg:#62a0ea"
format = '[ $symbol($version) ]($style)'

# Docker
[docker_context]
symbol = "ğŸ‹"
style = "fg:black bg:#99c1f1"
format = '[ $symbol $context ]($style) $path'

# Time
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:black bg:#deddda"
format = '[ $time]($style)'
